#!/bin/bash

# Really shitty shell script to init a new project file
# By Justus Languell, 2021
# Not exacly proud of it tho /:

mkdir $1

echo cmake_minimum_required\(VERSION 2.8\) > $1/CMakeLists.txt
echo project\( DisplayImage \) >> $1/CMakeLists.txt
echo find_package\( OpenCV REQUIRED \) >> $1/CMakeLists.txt
echo include_directories\( \${OpenCV_INCLUDE_DIRS} \) >> $1/CMakeLists.txt
echo add_executable\( $1 $1.cpp\) >> $1/CMakeLists.txt
echo target_link_libraries\( $1 \${OpenCV_LIBS} \) >> $1/CMakeLists.txt

echo "// This is the main file" > $1/$1.cpp
cd $1
